feat: add git.toggleVirtualText command
neoclide/coc-git pull request #118
Opened 2020-06-22 00:09 UTC by antoinemadec

I think it's a nice feature to add.
It was already requested in #80.

The code might not be the cleanest as I am not familiar with JS.
I tried to mimic what was already there. The feature works fine for me.

Thanks for the great extension!
Antoine

2020-07-02 22:07 UTC, antoinemadec commented
@chemzqm , did you have time to look at this?
Is this a feature that you'd consider add to ``coc-git```?

2020-07-03 06:16 UTC, chemzqm requested changes

2020-07-03 06:16 UTC, chemzqm commented on src/manager.ts
> +    this.config.update('addGBlameToVirtualText', !enabled, true)
We don't recommended update user's configuration when possible.

2020-07-03 06:18 UTC, chemzqm commented
You should implement show and hide virtualText from coc-git, instead of change user configuration.

2020-09-17 10:04 UTC, chemzqm commented
`call coc#config('git.addGBlameToVirtualText', v:false)` could work now.

2020-09-17 10:04 UTC, closed without merging